import * as stylex from '@stylexjs/stylex';
import { tokens, media } from '#lib/tokens.stylex.ts';
export const styles = stylex.create({
  welcomeBanner: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#edf1fb',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#e3e9f7',
    borderRadius: 13,
    paddingBlock: 24,
    paddingInline: { default: 32, [media.mobile]: 23 },
    marginBottom: 34,
    overflow: 'hidden',
    minHeight: 215,
    position: 'relative'
  },
  bannerContent: { position: 'relative', zIndex: 1 },
  bannerLabel: {
    fontSize: 10,
    color: '#677aa7',
    display: 'flex',
    alignItems: 'center',
    gap: 7,
    marginBottom: 12
  },
  bannerDot: { width: 5, height: 5, borderRadius: '50%', backgroundColor: '#97a8d6' },
  bannerTitle: { fontSize: 29, lineHeight: 1.15, letterSpacing: -1, color: '#354976' },
  bannerText: {
    fontSize: 12,
    color: '#6d7f9f',
    marginTop: 10,
    lineHeight: 1.7,
    maxWidth: { default: 400, [media.mobile]: 195 }
  },
  bannerButton: {
    borderWidth: 0,
    backgroundColor: 'transparent',
    color: '#4c67b1',
    padding: 0,
    fontSize: 11,
    fontWeight: 600,
    display: 'flex',
    gap: 5,
    alignItems: 'center',
    marginTop: 16
  },
  desktopBr: { display: { default: 'inline', [media.mobile]: 'none' } },
  artwork: {
    flexShrink: 0,
    width: { default: 310, '@media (max-width: 980px)': 240 },
    height: 170,
    position: { default: 'static', [media.mobile]: 'absolute' },
    right: { default: 'auto', [media.mobile]: -85 },
    bottom: 0,
    opacity: { default: 1, [media.mobile]: 0.65 }
  },
  contentGrid: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'minmax(0,1fr) 244px',
      '@media (max-width: 1250px)': 'minmax(0,1fr) 214px',
      '@media (max-width: 980px)': '1fr'
    },
    gap: { default: 25, '@media (max-width: 1250px)': 18 }
  },
  peopleSection: { minWidth: 0 },
  sectionTop: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 18,
    height: 24
  },
  sectionTitle: { fontSize: 20, display: 'flex', gap: 10, alignItems: 'center' },
  count: {
    fontFamily: tokens.font,
    fontSize: 11,
    display: 'grid',
    placeItems: 'center',
    minWidth: 23,
    height: 21,
    backgroundColor: '#eceff4',
    color: '#738095',
    borderRadius: 6
  },
  privateCaption: {
    fontSize: 10,
    display: { default: 'flex', [media.mobile]: 'none' },
    alignItems: 'center',
    gap: 5,
    color: '#7e899b'
  },
  tabs: {
    display: 'flex',
    alignItems: 'center',
    gap: { default: 22, [media.mobile]: 18 },
    paddingInline: { default: 20, [media.mobile]: 15 },
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.line,
    height: 52
  },
  tab: {
    backgroundColor: 'transparent',
    borderWidth: 0,
    borderBottomWidth: 2,
    borderBottomStyle: 'solid',
    borderBottomColor: 'transparent',
    height: '100%',
    paddingTop: 2,
    paddingBottom: 0,
    paddingInline: 0,
    color: '#7f899c',
    fontSize: 11,
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    whiteSpace: 'nowrap'
  },
  chosen: { color: tokens.blue, borderBottomColor: tokens.blue, fontWeight: 600 },
  tabCount: {
    backgroundColor: '#eef1fc',
    color: '#667eb9',
    borderRadius: 4,
    fontSize: 9,
    paddingBlock: 1,
    paddingInline: 5
  },
  tableToolbar: {
    display: 'flex',
    gap: 14,
    paddingBlock: 15,
    paddingInline: 18,
    alignItems: 'center'
  },
  searchBox: {
    display: 'flex',
    alignItems: 'center',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: tokens.line,
    borderRadius: 7,
    gap: 9,
    paddingInline: 11,
    flexGrow: 1,
    minWidth: 0,
    color: '#8893a6'
  },
  searchInput: {
    borderWidth: 0,
    backgroundColor: 'transparent',
    minHeight: 34,
    fontSize: 11,
    paddingBlock: 6,
    paddingInline: 0,
    marginTop: 0
  },
  searchHint: { color: '#a7aebc', fontSize: 17 },
  sortControl: {
    display: 'flex',
    alignItems: 'center',
    gap: 5,
    color: '#929bac',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: tokens.line,
    borderRadius: 6,
    paddingInline: 7
  },
  sortSelect: {
    width: 74,
    borderWidth: 0,
    margin: 0,
    paddingBlock: 7,
    paddingInline: 0,
    minHeight: 34,
    color: '#738095',
    fontSize: 11
  },
  table: { width: '100%', borderCollapse: 'collapse', textAlign: 'left' },
  th: {
    backgroundColor: '#fafbfc',
    fontSize: 10,
    fontWeight: 500,
    color: '#7e8a9d',
    height: 35,
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: '#f0f1f5',
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.line
  },
  firstCell: { paddingLeft: 20 },
  td: {
    height: 75,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: '#eff1f5',
    fontSize: 11,
    paddingRight: 12
  },
  row: { backgroundColor: { default: 'transparent', [media.hover]: { ':hover': '#fcfcff' } } },
  lastCell: { paddingRight: 12, width: 35 },
  locationCell: { display: { default: 'table-cell', '@media (max-width: 1250px)': 'none' } },
  emailCell: { display: { default: 'table-cell', [media.mobile]: 'none' } },
  personButton: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    borderWidth: 0,
    backgroundColor: 'transparent',
    paddingBlock: 8,
    paddingInline: 0,
    textAlign: 'left',
    color: { default: tokens.ink, [media.hover]: { ':hover': tokens.blue } },
    width: '100%'
  },
  personName: { display: 'flex', alignItems: 'center', gap: 6, fontSize: 12, fontWeight: 500 },
  personPhone: { display: 'block', fontSize: 10, color: '#7e8a9e', marginTop: 3 },
  tableEmail: { color: '#748097', fontSize: 11 },
  location: { color: '#7b889b', fontSize: 11, whiteSpace: 'nowrap' },
  locationRegion: { color: '#8e98a8' },
  tableFooter: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: 12,
    paddingBlock: 13,
    paddingInline: 19,
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: tokens.line,
    color: '#7f8c9d',
    fontSize: 9
  },
  footerNote: { display: { default: 'inline', '@media (max-width: 1250px)': 'none' } },
  tinyHeart: { fontSize: 12, paddingLeft: 3, color: '#929bb7' },
  googleNudge: { display: 'flex', alignItems: 'center', gap: 13, paddingTop: 21, paddingInline: 4 },
  googleIcon: {
    backgroundColor: tokens.paper,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: tokens.line,
    width: 35,
    height: 35,
    display: 'grid',
    placeItems: 'center',
    borderRadius: 8,
    fontFamily: 'Arial,sans-serif',
    fontSize: 19,
    fontWeight: 600,
    color: '#6489c2'
  },
  nudgeText: { flexGrow: 1 },
  nudgeTitle: { display: 'block', fontSize: 11, fontWeight: 500, color: '#65738b' },
  nudgeDescription: { fontSize: 10, color: '#8591a2', marginTop: 3 },
  nudgeLink: { color: '#7b8bb5', marginLeft: 'auto' },
  rightRail: {
    paddingTop: { default: 42, '@media (max-width: 980px)': 0 },
    display: { default: 'block', '@media (max-width: 980px)': 'grid' },
    gridTemplateColumns: { default: '1fr 1fr', [media.mobile]: '1fr' },
    gap: 18
  },
  birthdayPanel: { paddingTop: 20, paddingInline: 18 },
  railHeading: { display: 'flex', alignItems: 'center', gap: 8 },
  railTitle: { fontSize: 17 },
  cakeIcon: { display: 'grid', placeItems: 'center', color: '#a99bb3' },
  railDescription: { color: '#818799', fontSize: 10, marginTop: 6 },
  birthdayList: { display: 'flex', flexDirection: 'column', gap: 18, marginBlock: 24 },
  birthdayPerson: {
    display: 'flex',
    alignItems: 'center',
    gap: 9,
    textAlign: 'left',
    borderWidth: 0,
    backgroundColor: 'transparent',
    padding: 0,
    color: tokens.ink,
    width: '100%'
  },
  birthdayInfo: { flexGrow: 1 },
  birthdayName: { fontSize: 10, fontWeight: 500, display: 'block' },
  birthdayDate: { fontSize: 9, color: '#7f8b9d', display: 'block', marginTop: 4 },
  daysUntil: {
    fontSize: 9,
    paddingBlock: 3,
    paddingInline: 5,
    borderRadius: 4,
    backgroundColor: '#f5f2f9',
    color: '#917b9f'
  },
  birthdayNote: {
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: tokens.line,
    paddingBlock: 13,
    fontSize: 9,
    color: '#8c829c',
    display: 'flex',
    alignItems: 'center',
    gap: 8
  },
  birthdaySpark: { fontSize: 15, color: '#a794b5' },
  railEmpty: { fontSize: 12, color: tokens.muted, marginBlock: 25 },
  invitationNote: {
    marginTop: { default: 23, '@media (max-width: 980px)': 0 },
    paddingTop: 24,
    paddingInline: 21,
    paddingBottom: 20,
    backgroundColor: tokens.sage,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#e8ede3',
    borderRadius: 12,
    position: 'relative',
    overflow: 'hidden',
    display: { default: 'block', [media.mobile]: 'none' }
  },
  linkSymbol: { display: 'block', color: '#91a584', marginBottom: 13 },
  invitationTitle: { fontSize: 18, lineHeight: 1.3, maxWidth: 170, color: '#637659' },
  invitationText: { fontSize: 11, lineHeight: 1.8, color: '#7a8871', marginTop: 11 },
  invitationLink: {
    fontSize: 10,
    color: '#6d825e',
    display: 'flex',
    alignItems: 'center',
    gap: 5,
    marginTop: 15
  },
  noteCircles: { display: 'flex', alignItems: 'center', marginTop: 25 },
  noteCircle: {
    width: 27,
    height: 27,
    backgroundColor: '#e2e9da',
    borderRadius: '50%',
    borderWidth: 2,
    borderStyle: 'solid',
    borderColor: tokens.sage,
    display: 'grid',
    placeItems: 'center',
    fontSize: 9,
    color: '#96a288',
    marginLeft: -5
  },
  dottedCircle: {
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#c3ccba',
    backgroundColor: 'transparent',
    width: 22,
    height: 22,
    marginLeft: 4
  }
});
